name: CI/CD · Azure Functions (Flex · prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'fa-dq-demo'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    name: CI (build & tests)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create venv
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests (pytest)
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest -q
          else
            echo "No tests found - skipping"
          fi

      - name: Build artifact (source only)
        run: |
          zip -r release.zip "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" \
            -x "venv/**" ".git/**" ".github/**" "release.zip" "__pycache__/**" "*.pyc"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: release.zip

  deploy:
    name: Deploy → production (Flex)
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app

      - name: Unzip
        run: |
          unzip release.zip
          rm release.zip

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8D8A339E282D4C2E97AEB62491F36810 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_859CB250CB8A45CE9C932F14FF7D920A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80E0E8257C87497E8638342F7AFA0812 }}

      - name: Deploy to Azure Functions (Flex · remote build)
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          remote-build: true
          respect-funcignore: true
          # No slot-name aquí: Flex Consumption no soporta slots; deploy va al slot 'production' por defecto.
